import { NextResponse } from "next/server";
import { reportPdfRepository } from "@/db/repository";
import { exportReport } from "@/lib/export";
import { loadReportData } from "@/lib/export/load-report";
import { assessmentIdSchema, exportFormatSchema } from "@/server/validation";
import { getClientIp } from "@/server/ip";
import { rateLimiter } from "@/server/bootstrap";
import { IP_RATE_LIMIT, RATE_WINDOW_MS } from "@/server/rate-limit";

export const runtime = "nodejs";
export const maxDuration = 60;
export const dynamic = "force-dynamic";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  if (!assessmentIdSchema.safeParse(id).success) {
    return NextResponse.json({ code: "NOT_FOUND" }, { status: 404 });
  }
  const format = exportFormatSchema.safeParse(
    new URL(req.url).searchParams.get("format"),
  );
  if (!format.success) {
    return NextResponse.json({ code: "VALIDATION_ERROR" }, { status: 400 });
  }

  // Fast path: serve the stored PDF (generated by the worker after completion).
  const stored = await reportPdfRepository.findByAssessment(id);
  if (stored) {
    const body = Buffer.from(stored.pdf, "base64");
    return new NextResponse(new Uint8Array(body), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="assessment-${id}.pdf"`,
        "Cache-Control": "public, max-age=3600",
      },
    });
  }

  // Fallback: on-demand render (public + expensive → per-IP rate limited).
  const limited = await rateLimiter.check(`export:${getClientIp(req)}`, IP_RATE_LIMIT, RATE_WINDOW_MS);
  if (!limited.allowed) {
    return NextResponse.json({ code: "RATE_LIMITED" }, { status: 429 });
  }

  const { assessment, report } = await loadReportData(id);
  if (assessment.status !== "completed") {
    return NextResponse.json(
      { code: "CONFLICT", status: assessment.status },
      { status: 409 },
    );
  }

  const result = await exportReport(report, format.data);
  return new NextResponse(new Uint8Array(result.body), {
    headers: {
      "Content-Type": result.contentType,
      "Content-Disposition": `attachment; filename="assessment-${id}.${format.data}"`,
    },
  });
}
