import type { AiSettings } from "./settings";
import { judgeableFromScreenshot } from "./testability";

export interface ScAiConfig {
  sc: string;
  instructionId: string;
  modality: "vision" | "audio";
  judgeable: boolean;
  instruction: string;
  whatToLookFor: string[];
  passRequires: string[];
  failRequires: string[];
  examples?: { pass?: string | undefined; fail?: string | undefined } | undefined;
  ruleId: string;
  description: string;
  recommendation: string;
  help: string;
  source: string;
  notes: string;
  settings?: AiSettings | undefined;
  enabled: boolean;
}

// Vision SCs are `judgeable` when a screenshot alone can decide them; audio SCs
// are always judgeable from the page's media (their presence is gated elsewhere).
function cfg(
  sc: string,
  instructionId: string,
  modality: "vision" | "audio",
  body: Omit<ScAiConfig, "sc" | "instructionId" | "modality" | "judgeable" | "enabled">,
): ScAiConfig {
  return {
    sc,
    instructionId,
    modality,
    judgeable: modality === "vision" ? judgeableFromScreenshot(sc) : true,
    enabled: true,
    ...body,
  };
}

const SOURCE = (sc: string) => `https://www.w3.org/WAI/WCAG22/Understanding/${sc}.html`;

export const DEFAULT_AI_CONFIGS: Record<string, ScAiConfig> = {
  // ---- vision (AI map) ----
  "1.3.3": cfg("1.3.3", "1.3.3.1", "vision", {
    instruction: "Instructions do not rely solely on sensory characteristics (shape, color, position, sound).",
    whatToLookFor: ["visible instructions that reference color, shape, size, position, or sound alone"],
    passRequires: ["any instruction referencing a visual/sensory trait is paired with a non-sensory cue or label"],
    failRequires: ["a visible instruction relies on color/shape/position alone (e.g. \"click the red button\")"],
    ruleId: "ai-sensory-characteristics",
    description: "Instructions rely on sensory characteristics alone",
    recommendation: "Add a text label or name to the element so instructions need not reference color, shape, or position.",
    help: "Instructions must not rely on sensory characteristics alone",
    source: SOURCE("sensory-characteristics"),
    notes: "drafted 2026-08-20",
  }),
  "1.4.5": cfg("1.4.5", "1.4.5.1", "vision", {
    instruction: "Text is not rendered as an image where real text could convey it.",
    whatToLookFor: ["rasterised/graphic text embedded in images"],
    passRequires: ["no text appears to be rendered as an image (or it is a logo/essential graphic)"],
    failRequires: ["body/heading text is visibly rendered as an image rather than real text"],
    ruleId: "ai-images-of-text",
    description: "Text is rendered as an image instead of real text",
    recommendation: "Replace the image of text with real, selectable text (reserve image-of-text for logos and essential graphics).",
    help: "Images of text must not be used when real text would work",
    source: SOURCE("images-of-text"),
    notes: "drafted 2026-08-20",
  }),
  "1.4.9": cfg("1.4.9", "1.4.9.1", "vision", {
    instruction: "Text is not rendered as an image (no exception).",
    whatToLookFor: ["any text rendered as an image"],
    passRequires: ["no text is rendered as an image"],
    failRequires: ["text is visibly rendered as an image"],
    ruleId: "ai-images-of-text-no-exception",
    description: "Text is rendered as an image",
    recommendation: "Use real text everywhere, including for logos and decorative graphics.",
    help: "Images of text are not allowed (no exception)",
    source: SOURCE("images-of-text-no-exception"),
    notes: "drafted 2026-08-20",
  }),
  "2.4.9": cfg("2.4.9", "2.4.9.1", "vision", {
    instruction: "Each link's purpose is clear from its link text alone.",
    whatToLookFor: ["links whose visible text is ambiguous out of context (\"click here\", \"learn more\", \"read more\")"],
    passRequires: ["every link's visible text clearly conveys its destination/purpose"],
    failRequires: ["a link's text alone is ambiguous (e.g. multiple \"click here\" links to different targets)"],
    ruleId: "ai-link-purpose",
    description: "A link's purpose is not clear from its text alone",
    recommendation: "Rewrite the link text to describe its destination (avoid generic phrases like \"click here\").",
    help: "Link purpose must be clear from the link text alone",
    source: SOURCE("link-purpose-link-only"),
    notes: "drafted 2026-08-20",
  }),
  "3.1.3": cfg("3.1.3", "3.1.3.1", "vision", {
    instruction: "Unusual words or jargon have a definition available.",
    whatToLookFor: ["domain-specific jargon, technical terms, or idioms in the visible text"],
    passRequires: ["no unusual words/jargon are visible, or each has a visible/adjacent definition"],
    failRequires: ["unexplained jargon/technical terms are visible with no definition in sight"],
    ruleId: "ai-unusual-words",
    description: "Unusual words or jargon are used without a definition",
    recommendation: "Provide a definition (inline, glossary link, or adjacent explanation) for each unusual term.",
    help: "Unusual words and jargon must be defined",
    source: SOURCE("unusual-words"),
    notes: "drafted 2026-08-20",
  }),
  "3.1.4": cfg("3.1.4", "3.1.4.1", "vision", {
    instruction: "Abbreviations have their expanded form available.",
    whatToLookFor: ["abbreviations or acronyms in the visible text"],
    passRequires: ["no abbreviations are visible, or each is expanded inline or via a definition"],
    failRequires: ["an unexplained abbreviation/acronym is visible with no expansion"],
    ruleId: "ai-abbreviations",
    description: "An abbreviation is used without its expanded form",
    recommendation: "Expand the abbreviation on first use or link it to a definition.",
    help: "Abbreviations must be expanded",
    source: SOURCE("abbreviations"),
    notes: "drafted 2026-08-20",
  }),
  // ---- vision (MIXED ai instructions) ----
  "1.4.1": cfg("1.4.1", "1.4.1.2", "vision", {
    instruction: "Color is not the only means of conveying information.",
    whatToLookFor: ["information distinguished only by color (e.g. required fields in red, links distinguished only by color)"],
    passRequires: ["color differences are accompanied by a non-color cue (underline, icon, text, pattern)"],
    failRequires: ["information is conveyed by color alone with no non-color cue"],
    ruleId: "ai-use-of-color",
    description: "Color is used as the only way to convey information",
    recommendation: "Add a non-color cue (underline, icon, label, or pattern) wherever color carries meaning.",
    help: "Color must not be the only means of conveying information",
    source: SOURCE("use-of-color"),
    notes: "drafted 2026-08-20",
  }),
  "2.4.4": cfg("2.4.4", "2.4.4.2", "vision", {
    instruction: "Each link's purpose is clear from its text in context.",
    whatToLookFor: ["links whose purpose is unclear even with surrounding context"],
    passRequires: ["every link's purpose is clear from its text plus surrounding context"],
    failRequires: ["a link's purpose is unclear from its text and context"],
    ruleId: "ai-link-purpose-context",
    description: "A link's purpose is not clear from its context",
    recommendation: "Clarify the link text or add surrounding context so the destination is unambiguous.",
    help: "Link purpose must be clear in context",
    source: SOURCE("link-purpose-in-context"),
    notes: "drafted 2026-08-20",
  }),
  "2.4.6": cfg("2.4.6", "2.4.6.2", "vision", {
    instruction: "Headings and labels are descriptive.",
    whatToLookFor: ["headings/labels that are generic or misleading for their content"],
    passRequires: ["visible headings and labels clearly describe their topic/purpose"],
    failRequires: ["a heading or label is clearly non-descriptive (e.g. \"More\" for unrelated sections)"],
    ruleId: "ai-descriptive-headings",
    description: "A heading or label does not describe its content",
    recommendation: "Rewrite the heading or label to describe the content it introduces.",
    help: "Headings and labels must be descriptive",
    source: SOURCE("headings-and-labels"),
    notes: "drafted 2026-08-20",
  }),
  // ---- vision, NOT judgeable from screenshot (force needs-review) ----
  "1.3.2": cfg("1.3.2", "1.3.2.1", "vision", {
    instruction: "Content reads in a meaningful sequence when linearised.",
    whatToLookFor: ["the DOM reading order of text blocks (use get_reading_order)"],
    passRequires: ["the reading order presents content in a meaningful, logical sequence"],
    failRequires: ["the reading order reorders content illogically (e.g. sidebar/footer text read before the main content)"],
    ruleId: "ai-meaningful-sequence",
    description: "Content order may not follow a meaningful sequence",
    recommendation: "Review the DOM/source order so it matches the visual reading order.",
    help: "Content must read in a meaningful order",
    source: SOURCE("meaningful-sequence"),
    notes: "not screenshot-judgeable — needs DOM order",
  }),
  "1.3.6": cfg("1.3.6", "1.3.6.1", "vision", {
    instruction: "The purpose of icons, regions, and controls is programmatically identifiable.",
    whatToLookFor: ["controls, icons, and regions and their accessible names/roles (use get_a11y_tree)"],
    passRequires: ["every control and landmark exposes a meaningful accessible name/role"],
    failRequires: ["an icon-only control or a region lacks a programmatic name/role"],
    ruleId: "ai-identify-purpose",
    description: "Icon/region purpose may not be programmatically identifiable",
    recommendation: "Expose the purpose via accessible name/role/landmarks.",
    help: "Purpose must be programmatically identifiable",
    source: SOURCE("identify-purpose"),
    notes: "not screenshot-judgeable — needs programmatic inspection",
  }),
  "1.4.13": cfg("1.4.13", "1.4.13.1", "vision", {
    instruction: "Content on hover or focus is dismissible, hoverable, and persistent.",
    whatToLookFor: ["popovers/tooltips revealed on hover or focus (use trigger_hover, trigger_focus)"],
    passRequires: ["revealed content is dismissible, hoverable, and persistent while relevant — or there is no hover/focus-revealed content"],
    failRequires: ["hover/focus-revealed content cannot be dismissed or obscures other content"],
    ruleId: "ai-content-on-hover-focus",
    description: "Hover/focus-revealed content may obscure or trap",
    recommendation: "Ensure popovers can be dismissed, hovered, and persist while relevant.",
    help: "Hover/focus content must be dismissible and persistent",
    source: SOURCE("content-on-hover-or-focus"),
    notes: "not screenshot-judgeable — needs focus/hover states",
  }),
  "2.3.3": cfg("2.3.3", "2.3.3.1", "vision", {
    instruction: "Motion triggered by interaction can be disabled.",
    whatToLookFor: ["interaction-triggered motion/animations and whether prefers-reduced-motion is honoured (use query_all, inspect_element)"],
    passRequires: ["no interaction-triggered motion, or it respects prefers-reduced-motion / offers a disable control"],
    failRequires: ["non-essential motion runs with no reduced-motion alternative"],
    ruleId: "ai-animation-from-interactions",
    description: "Interaction-triggered animation may not be preventable",
    recommendation: "Provide a reduced-motion setting or a control to disable non-essential motion.",
    help: "Interaction-triggered motion must be preventable",
    source: SOURCE("animation-from-interactions"),
    notes: "not screenshot-judgeable — needs interaction",
  }),
  "3.1.5": cfg("3.1.5", "3.1.5.1", "vision", {
    instruction: "Text is written at a reading level appropriate for the audience.",
    whatToLookFor: ["the complexity of the visible prose (use get_reading_order)"],
    passRequires: ["the prose is plain and appropriate for the audience, or a plain-language summary is provided"],
    failRequires: ["text is jargon-heavy/technical with no plain-language alternative"],
    ruleId: "ai-reading-level",
    description: "Text may be more complex than the audience's reading level",
    recommendation: "Provide a plain-language summary or simplify the prose.",
    help: "Text should match the audience's reading level",
    source: SOURCE("reading-level"),
    notes: "not screenshot-judgeable — needs full-text extraction",
  }),
  "3.3.1": cfg("3.3.1", "3.3.1.1", "vision", {
    instruction: "Input errors are identified in text and described to the user.",
    whatToLookFor: ["form fields and their error states (use trigger_input_and_errors)"],
    passRequires: ["a form with invalid input shows a text error per invalid field — or the page has no forms"],
    failRequires: ["an invalid field is not identified with a text error"],
    ruleId: "ai-error-identification",
    description: "Input errors may not be identified in text",
    recommendation: "Show a text error message next to each invalid field.",
    help: "Errors must be identified and described",
    source: SOURCE("error-identification"),
    notes: "not screenshot-judgeable — needs an error state",
  }),
  "3.3.3": cfg("3.3.3", "3.3.3.1", "vision", {
    instruction: "Error messages include a suggestion for how to fix the problem.",
    whatToLookFor: ["error messages and whether they suggest a fix (use trigger_input_and_errors)"],
    passRequires: ["each error message includes a corrective suggestion — or there are no errors/forms"],
    failRequires: ["an error message lacks a suggestion for correction"],
    ruleId: "ai-error-suggestion",
    description: "Error messages may not suggest how to correct the error",
    recommendation: "Include a corrective suggestion in each error message.",
    help: "Error messages must suggest a fix",
    source: SOURCE("error-suggestion"),
    notes: "not screenshot-judgeable — needs an error state",
  }),
  "1.1.1": cfg("1.1.1", "1.1.1.2", "vision", {
    instruction: "Alternative text is meaningful (not just a filename or placeholder).",
    whatToLookFor: ["images and their alt text (use get_images_and_alt)"],
    passRequires: ["each meaningful image has descriptive alt text and decorative images are alt=\"\" — or there are no images"],
    failRequires: ["a meaningful image has a filename/placeholder alt or no alt"],
    ruleId: "ai-meaningful-alt",
    description: "Alternative text may not meaningfully describe the image",
    recommendation: "Ensure the alt text describes the image's content and function.",
    help: "Alternative text must be meaningful",
    source: SOURCE("non-text-content"),
    notes: "not screenshot-judgeable — needs the alt attribute",
  }),
  // ---- audio (judged from media, gated on media presence) ----
  "1.2.1": cfg("1.2.1", "1.2.1.2", "audio", {
    instruction: "A transcript conveys the same information as the audio/video.",
    whatToLookFor: ["a linked or adjacent text transcript for the media"],
    passRequires: ["a transcript is present and conveys the media's information"],
    failRequires: ["media is present with no transcript, or the transcript omits key information"],
    ruleId: "ai-media-transcript",
    description: "Audio/video has no equivalent text transcript",
    recommendation: "Provide a text transcript that conveys the full audio/video content.",
    help: "Audio/video must have a text transcript",
    source: SOURCE("audio-only-and-video-only-prerecorded"),
    notes: "drafted 2026-08-20",
  }),
  "1.2.2": cfg("1.2.2", "1.2.2.2", "audio", {
    instruction: "Captions are accurate and synchronised with the spoken audio.",
    whatToLookFor: ["captions that match the spoken content and timing"],
    passRequires: ["captions are present, accurate, and synchronised"],
    failRequires: ["captions are missing, inaccurate, or out of sync"],
    ruleId: "ai-captions-accurate",
    description: "Captions are missing or inaccurate",
    recommendation: "Provide accurate, synchronised captions for all spoken audio.",
    help: "Captions must be accurate and synchronised",
    source: SOURCE("captions-prerecorded"),
    notes: "drafted 2026-08-20",
  }),
  "1.2.3": cfg("1.2.3", "1.2.3.1", "audio", {
    instruction: "An audio description or text alternative conveys the visual information.",
    whatToLookFor: ["an audio description track or a descriptive transcript for the video"],
    passRequires: ["visual information is conveyed via audio description or a text alternative"],
    failRequires: ["video has no audio description and visual info is not otherwise conveyed"],
    ruleId: "ai-audio-description",
    description: "Video lacks an audio description or text alternative",
    recommendation: "Add an audio description or a descriptive transcript for the visual content.",
    help: "Video must have an audio description or text alternative",
    source: SOURCE("audio-description-or-media-alternative-prerecorded"),
    notes: "drafted 2026-08-20",
  }),
  "1.2.5": cfg("1.2.5", "1.2.5.1", "audio", {
    instruction: "An audio description describes the important visual content.",
    whatToLookFor: ["an audio description track describing visual scenes/actions"],
    passRequires: ["an audio description conveys the important visual content"],
    failRequires: ["important visual content is not described"],
    ruleId: "ai-audio-description-prerecorded",
    description: "Video lacks an audio description of important visual content",
    recommendation: "Provide an audio description for the important visual content.",
    help: "Video must have an audio description",
    source: SOURCE("audio-description-prerecorded"),
    notes: "drafted 2026-08-20",
  }),
  "1.2.6": cfg("1.2.6", "1.2.6.1", "audio", {
    instruction: "Sign-language interpretation is provided.",
    whatToLookFor: ["a sign-language video or track"],
    passRequires: ["sign-language interpretation is provided for the audio content"],
    failRequires: ["no sign-language interpretation is present"],
    ruleId: "ai-sign-language",
    description: "Sign-language interpretation is not provided",
    recommendation: "Provide a sign-language interpretation of the audio content.",
    help: "Sign-language interpretation must be provided",
    source: SOURCE("sign-language-prerecorded"),
    notes: "drafted 2026-08-20",
  }),
  "1.2.7": cfg("1.2.7", "1.2.7.1", "audio", {
    instruction: "Extended audio description conveys all visual detail.",
    whatToLookFor: ["an extended audio description track"],
    passRequires: ["all visual detail is conveyed via extended audio description"],
    failRequires: ["visual detail is omitted from the audio description"],
    ruleId: "ai-extended-audio-description",
    description: "Visual detail is not fully described",
    recommendation: "Provide an extended audio description conveying all visual detail.",
    help: "Extended audio description must convey all visual detail",
    source: SOURCE("extended-audio-description-prerecorded"),
    notes: "drafted 2026-08-20",
  }),
  "1.4.7": cfg("1.4.7", "1.4.7.1", "audio", {
    instruction: "Background audio is absent, can be turned off, or is 20dB below foreground speech.",
    whatToLookFor: ["background music/sounds during speech"],
    passRequires: ["no background audio, or it is clearly low/controllable"],
    failRequires: ["background audio clearly interferes with the foreground speech"],
    ruleId: "ai-low-background-audio",
    description: "Background audio interferes with foreground speech",
    recommendation: "Remove or lower background audio (or provide a control to turn it off).",
    help: "Background audio must not interfere with speech",
    source: SOURCE("low-or-no-background-audio"),
    notes: "drafted 2026-08-20",
  }),
  // ---- tool-judgeable interaction/state SCs (decided with browser tools) ----
  "2.4.11": cfg("2.4.11", "2.4.11.1", "vision", {
    instruction: "A component receiving keyboard focus is not entirely hidden by sticky/fixed content.",
    whatToLookFor: ["sticky headers/footers/dialogs that could cover the focused element"],
    passRequires: ["trigger_focus + inspect_element show the focused element is not covered"],
    failRequires: ["the focused element is obscured by a sticky region"],
    ruleId: "ai-focus-not-obscured",
    description: "Focused element may be obscured by sticky content",
    recommendation: "Scroll focused elements into view above sticky regions.",
    help: "Focus must not be obscured",
    source: SOURCE("focus-not-obscured-minimum"),
    notes: "judged with tools",
  }),
  "2.4.12": cfg("2.4.12", "2.4.12.1", "vision", {
    instruction: "A component receiving focus is fully visible (not partially obscured by sticky/fixed content).",
    whatToLookFor: ["sticky content overlapping any part of the focused element"],
    passRequires: ["the focused element is entirely visible after trigger_focus + inspect_element"],
    failRequires: ["any part of the focused element is covered"],
    ruleId: "ai-focus-not-obscured-enhanced",
    description: "Focused element is partially obscured by sticky content",
    recommendation: "Ensure the full focused element is visible above sticky regions.",
    help: "Focus must not be obscured (enhanced)",
    source: SOURCE("focus-not-obscured-enhanced"),
    notes: "judged with tools",
  }),
  "2.4.13": cfg("2.4.13", "2.4.13.1", "vision", {
    instruction: "The keyboard focus indicator is clearly visible (a non-none outline/ring).",
    whatToLookFor: ["a visible focus outline on the focused element"],
    passRequires: ["trigger_focus + inspect_element report outline-style != none and outline-width > 0"],
    failRequires: ["the focused element has no visible outline (outline-style none or width 0)"],
    ruleId: "ai-focus-appearance",
    description: "Focus indicator is not clearly visible",
    recommendation: "Add a visible focus outline (>= 2px, sufficient contrast).",
    help: "Focus indicator must be visible",
    source: SOURCE("focus-appearance"),
    notes: "judged with tools",
  }),
  "3.2.6": cfg("3.2.6", "3.2.6.1", "vision", {
    instruction: "Help is available in a consistent location (contact/help/support link present).",
    whatToLookFor: ["a help/contact/support link or mechanism (use get_links)"],
    passRequires: ["a help mechanism is present on the page"],
    failRequires: ["no help/contact/support mechanism is found"],
    ruleId: "ai-consistent-help",
    description: "Help is not available in a consistent location",
    recommendation: "Provide a help/contact link in a consistent place.",
    help: "Help must be consistently available",
    source: SOURCE("consistent-help"),
    notes: "judged with tools",
  }),
  "3.2.1": cfg("3.2.1", "3.2.1.1", "vision", {
    instruction: "Receiving focus does not initiate a change of context.",
    whatToLookFor: ["controls whose focus triggers navigation, form submission, or a major layout/context change (use trigger_keyboard_traversal, inspect_element)"],
    passRequires: ["focusing a control does not change the context, or the change is expected and communicated"],
    failRequires: ["focusing a control unexpectedly navigates, submits a form, or changes context without warning"],
    ruleId: "ai-on-focus",
    description: "Focusing a control causes an unexpected change of context",
    recommendation: "Ensure moving focus to a control does not navigate, submit, or otherwise change context unexpectedly.",
    help: "Focus must not cause an unexpected change of context",
    source: SOURCE("on-focus"),
    notes: "judged with tools",
  }),
  "3.2.2": cfg("3.2.2", "3.2.2.1", "vision", {
    instruction: "Changing the value of a form control does not initiate a change of context.",
    whatToLookFor: ["selects/checkboxes/radios whose value change triggers navigation or a major context change (use trigger_keyboard_traversal, inspect_element)"],
    passRequires: ["changing a control's value does not change the context, or the change is expected and communicated"],
    failRequires: ["changing a control's value unexpectedly navigates or changes context without warning"],
    ruleId: "ai-on-input",
    description: "Changing a control's value causes an unexpected change of context",
    recommendation: "Ensure changing a control's value does not navigate or change context unexpectedly (or warn the user first).",
    help: "Input must not cause an unexpected change of context",
    source: SOURCE("on-input"),
    notes: "judged with tools",
  }),
  "4.1.3": cfg("4.1.3", "4.1.3.1", "vision", {
    instruction: "Dynamic status messages are exposed to assistive technology (role=status, role=alert, aria-live, or <output>).",
    whatToLookFor: ["regions with role=status/alert, aria-live, or <output> (use get_a11y_tree)"],
    passRequires: ["a status/alert/live region exists, or the page has no dynamic status content"],
    failRequires: ["dynamic content (form errors, cart updates) has no status/alert/live region"],
    ruleId: "ai-status-messages",
    description: "Status messages are not programmatically exposed",
    recommendation: "Wrap dynamic status messages in role=status/alert or aria-live.",
    help: "Status messages must be exposed to assistive technology",
    source: SOURCE("status-messages"),
    notes: "judged with tools",
  }),
  // ---- formerly manual-only, now agentic-eligible (interaction/cognitive) ----
  "2.1.3": cfg("2.1.3", "2.1.3.1", "vision", {
    instruction: "All functionality is operable through a keyboard interface without exception.",
    whatToLookFor: ["pointer-only controls or drag interactions without a keyboard equivalent (use trigger_keyboard_traversal, click)"],
    passRequires: ["every interactive control has a keyboard-operable equivalent"],
    failRequires: ["a control or interaction requires a pointer/touch gesture with no keyboard alternative"],
    ruleId: "ai-keyboard-no-exception",
    description: "Some functionality has no keyboard equivalent",
    recommendation: "Provide a keyboard-operable alternative for every pointer/touch control.",
    help: "All functionality must be keyboard operable",
    source: SOURCE("keyboard-no-exception"),
    notes: "agentic",
  }),
  "2.1.4": cfg("2.1.4", "2.1.4.1", "vision", {
    instruction: "Single-character keyboard shortcuts can be turned off, remapped, or are only active when the component has focus.",
    whatToLookFor: ["global single-key handlers (accesskey, keydown listeners) without a remap/disable mechanism"],
    passRequires: ["no single-character shortcuts, or they are focus-scoped / remappable / can be turned off"],
    failRequires: ["a single-letter shortcut fires globally with no way to disable or remap it"],
    ruleId: "ai-char-key-shortcuts",
    description: "A single-character shortcut cannot be turned off or remapped",
    recommendation: "Allow single-character shortcuts to be turned off, remapped, or active only on focus.",
    help: "Character key shortcuts must be remappable or disableable",
    source: SOURCE("character-key-shortcuts"),
    notes: "agentic",
  }),
  "2.2.4": cfg("2.2.4", "2.2.4.1", "vision", {
    instruction: "Interruptions (alerts, updates) can be postponed or suppressed by the user.",
    whatToLookFor: ["auto-modal popups, chat/notification overlays that cannot be dismissed/postponed"],
    passRequires: ["no interruptions, or they can be postponed/suppressed"],
    failRequires: ["an interruption cannot be postponed or dismissed"],
    ruleId: "ai-interruptions",
    description: "An interruption cannot be postponed or suppressed",
    recommendation: "Provide a way to postpone or suppress non-essential interruptions.",
    help: "Interruptions must be postponable or suppressible",
    source: SOURCE("interruptions"),
    notes: "agentic",
  }),
  "2.2.5": cfg("2.2.5", "2.2.5.1", "vision", {
    instruction: "Re-authenticating after a session expires does not cause loss of data.",
    whatToLookFor: ["login/session forms (use set_value, submit_form) and whether entered data is preserved"],
    passRequires: ["no re-authentication flow, or data is preserved through re-auth"],
    failRequires: ["re-authentication discards user-entered data"],
    ruleId: "ai-reauth",
    description: "Re-authentication causes loss of user data",
    recommendation: "Preserve user data through re-authentication.",
    help: "Re-authentication must not lose data",
    source: SOURCE("re-authenticating"),
    notes: "agentic",
  }),
  "2.2.6": cfg("2.2.6", "2.2.6.1", "vision", {
    instruction: "Users are warned before a session timeout that causes data loss.",
    whatToLookFor: ["timeout warnings (session expiry messaging, countdown)"],
    passRequires: ["no timeout, or users are warned and can extend before data loss"],
    failRequires: ["a timeout causes data loss without warning"],
    ruleId: "ai-timeouts",
    description: "A timeout causes data loss without warning",
    recommendation: "Warn users before a timeout and allow them to extend the session.",
    help: "Timeouts must be warned and extendable",
    source: SOURCE("timeouts"),
    notes: "agentic",
  }),
  "2.5.1": cfg("2.5.1", "2.5.1.1", "vision", {
    instruction: "Multipoint or path-based gestures have a single-pointer alternative.",
    whatToLookFor: ["pinch/zoom, multi-finger swipe, or drag-path interactions (maps, sliders, carousels)"],
    passRequires: ["no multipoint/path gestures, or a single-pointer/tap alternative exists"],
    failRequires: ["a function is only operable via a multipoint or path gesture"],
    ruleId: "ai-pointer-gestures",
    description: "A function requires a multipoint or path gesture",
    recommendation: "Provide a single-pointer (tap/click) alternative for complex gestures.",
    help: "Path-based gestures need a single-pointer alternative",
    source: SOURCE("pointer-gestures"),
    notes: "agentic",
  }),
  "2.5.4": cfg("2.5.4", "2.5.4.1", "vision", {
    instruction: "Motion actuation (shake, tilt) can be disabled, or an alternative interface exists.",
    whatToLookFor: ["devicemotion/orientation handlers without an alternative control"],
    passRequires: ["no motion actuation, or it can be disabled / an alternative exists"],
    failRequires: ["a function relies solely on motion actuation"],
    ruleId: "ai-motion-actuation",
    description: "Functionality relies on motion actuation without an alternative",
    recommendation: "Provide a non-motion alternative and allow motion to be disabled.",
    help: "Motion actuation must be disableable",
    source: SOURCE("motion-actuation"),
    notes: "agentic",
  }),
  "2.5.6": cfg("2.5.6", "2.5.6.1", "vision", {
    instruction: "Content can be operated with multiple input modalities (keyboard, pointer, touch).",
    whatToLookFor: ["controls that only respond to a single input type (hover-only, touch-only)"],
    passRequires: ["controls respond to multiple input mechanisms, or no input restriction exists"],
    failRequires: ["a control is restricted to a single input modality"],
    ruleId: "ai-concurrent-input",
    description: "Content is restricted to a single input modality",
    recommendation: "Ensure content works with keyboard, pointer, and touch.",
    help: "Concurrent input mechanisms must be supported",
    source: SOURCE("concurrent-input-mechanisms"),
    notes: "agentic",
  }),
  "3.1.6": cfg("3.1.6", "3.1.6.1", "vision", {
    instruction: "Pronunciation of ambiguous words is identified where meaning is unclear without it.",
    whatToLookFor: ["ambiguous words without a pronunciation hint"],
    passRequires: ["no ambiguous words, or pronunciation is identified"],
    failRequires: ["an ambiguous word lacks pronunciation identification where meaning depends on it"],
    ruleId: "ai-pronunciation",
    description: "Pronunciation of ambiguous words is not identified",
    recommendation: "Identify pronunciation for ambiguous words where meaning depends on it.",
    help: "Pronunciation must be identified where needed",
    source: SOURCE("pronunciation"),
    notes: "agentic",
  }),
  "3.2.3": cfg("3.2.3", "3.2.3.1", "vision", {
    instruction: "Navigation mechanisms are presented in the same relative order on every page.",
    whatToLookFor: ["nav links/order across pages (use get_a11y_tree, get_links)"],
    passRequires: ["navigation is consistent in order and content"],
    failRequires: ["navigation order or items differ across pages"],
    ruleId: "ai-consistent-nav",
    description: "Navigation is inconsistent across pages",
    recommendation: "Keep navigation links in the same relative order on every page.",
    help: "Navigation must be consistent across pages",
    source: SOURCE("consistent-navigation"),
    notes: "agentic (cross-page pass resolves deterministically when possible)",
  }),
  "3.2.4": cfg("3.2.4", "3.2.4.1", "vision", {
    instruction: "Components with the same function are identified consistently across pages.",
    whatToLookFor: ["the same destination/action labelled differently across pages (use get_links)"],
    passRequires: ["identical components use identical labels"],
    failRequires: ["the same component/destination is labelled differently across pages"],
    ruleId: "ai-consistent-identification",
    description: "Identical components are identified inconsistently",
    recommendation: "Use one consistent label for components with the same function.",
    help: "Identical components must be identified consistently",
    source: SOURCE("consistent-identification"),
    notes: "agentic (cross-page pass resolves deterministically when possible)",
  }),
  "3.2.5": cfg("3.2.5", "3.2.5.1", "vision", {
    instruction: "Changes of context are initiated only by user request, or a mechanism to turn them off exists.",
    whatToLookFor: ["auto-refresh, auto-redirect, or auto-advance that changes context without user action"],
    passRequires: ["context changes require user request or can be turned off"],
    failRequires: ["a context change occurs automatically without user request"],
    ruleId: "ai-change-on-request",
    description: "A change of context occurs without user request",
    recommendation: "Initiate context changes only on user request, or provide an off mechanism.",
    help: "Changes of context must be user-initiated",
    source: SOURCE("change-on-request"),
    notes: "agentic",
  }),
  "3.3.4": cfg("3.3.4", "3.3.4.1", "vision", {
    instruction: "Submissions causing legal/financial commitments or modifying/deleting user data are reversible, checked, or confirmed.",
    whatToLookFor: ["checkout/payment/delete forms (use set_value, submit_form) with confirm/review/cancel"],
    passRequires: ["no such forms, or a submission is reversible, checked, or confirmed"],
    failRequires: ["a legal/financial/data submission can proceed without confirmation/review"],
    ruleId: "ai-error-prevention",
    description: "A consequential submission lacks confirmation or review",
    recommendation: "Add a confirmation/review step, or make the action reversible.",
    help: "Consequential submissions must be confirmed",
    source: SOURCE("error-prevention-legal-financial-data"),
    notes: "agentic",
  }),
  "3.3.6": cfg("3.3.6", "3.3.6.1", "vision", {
    instruction: "All submissions are reversible, checked, or confirmed (AAA).",
    whatToLookFor: ["any form submission without a confirm/review step (use submit_form)"],
    passRequires: ["submissions are reversible, checked, or confirmed"],
    failRequires: ["a submission can proceed without confirmation/review"],
    ruleId: "ai-error-prevention-all",
    description: "A submission lacks confirmation or review",
    recommendation: "Provide confirmation, review, or reversibility for all submissions.",
    help: "All submissions must be confirmable",
    source: SOURCE("error-prevention-all"),
    notes: "agentic",
  }),
  "3.3.9": cfg("3.3.9", "3.3.9.1", "vision", {
    instruction: "Authentication does not rely on a cognitive function test (memorisation, transcription, puzzle).",
    whatToLookFor: ["CAPTCHA/puzzle/transcription or memorisation requirements (use inspect_element, query_all)"],
    passRequires: ["no cognitive test, or an alternative (password manager, magic link) is available"],
    failRequires: ["authentication requires a cognitive test with no alternative"],
    ruleId: "ai-accessible-auth",
    description: "Authentication requires a cognitive function test",
    recommendation: "Provide an alternative (password manager, magic link, no CAPTCHA).",
    help: "Authentication must not require a cognitive test",
    source: SOURCE("accessible-authentication"),
    notes: "agentic",
  }),
  "1.2.8": cfg("1.2.8", "1.2.8.1", "vision", {
    instruction: "An alternative for time-based media (full text transcript) is provided.",
    whatToLookFor: ["video/audio with a linked transcript (use get_links)"],
    passRequires: ["no time-based media, or a transcript is linked"],
    failRequires: ["time-based media has no linked transcript alternative"],
    ruleId: "ai-media-alternative",
    description: "Time-based media lacks a text alternative",
    recommendation: "Link a full text transcript for time-based media.",
    help: "Time-based media needs a transcript",
    source: SOURCE("media-alternative-prerecorded"),
    notes: "agentic",
  }),
  "1.4.8": cfg("1.4.8", "1.4.8.1", "vision", {
    instruction: "Text blocks can be presented with user-selectable foreground/background colours, width ≤ 80 chars, no full justification, and line spacing.",
    whatToLookFor: ["long text blocks with fixed colours, full justification, or no line spacing"],
    passRequires: ["no text blocks, or the visual-presentation requirements are met"],
    failRequires: ["a text block is fully justified / fixed-colour / over-wide without a conforming presentation"],
    ruleId: "ai-visual-presentation",
    description: "Text blocks do not meet visual presentation requirements",
    recommendation: "Allow user-selectable colours, limit width, and avoid full justification.",
    help: "Visual presentation of text must be configurable",
    source: SOURCE("visual-presentation"),
    notes: "agentic",
  }),
  "2.3.1": cfg("2.3.1", "2.3.1.1", "vision", {
    instruction: "Content does not flash more than three times per second (or is below the flash thresholds).",
    whatToLookFor: ["rapid flashing animation or video (inspect animation styles)"],
    passRequires: ["no flashing content"],
    failRequires: ["content flashes more than three times per second"],
    ruleId: "ai-three-flashes",
    description: "Content flashes more than three times per second",
    recommendation: "Remove or slow content that flashes more than three times per second.",
    help: "Content must not flash more than three times per second",
    source: SOURCE("three-flashes-or-below-threshold"),
    notes: "agentic (no-flashing rule resolves deterministically when possible)",
  }),
  "2.3.2": cfg("2.3.2", "2.3.2.1", "vision", {
    instruction: "Content does not flash more than three times in any one-second period (AAA).",
    whatToLookFor: ["rapid flashing animation or video"],
    passRequires: ["no flashing content"],
    failRequires: ["content flashes more than three times per second"],
    ruleId: "ai-three-flashes-aaa",
    description: "Content flashes more than three times per second",
    recommendation: "Remove or slow content that flashes more than three times per second.",
    help: "Content must not flash more than three times per second",
    source: SOURCE("three-flashes"),
    notes: "agentic",
  }),
  "1.3.1": cfg("1.3.1", "1.3.1.2", "vision", {
    instruction: "Information, structure, and relationships conveyed through presentation are available programmatically (and announced correctly by assistive technology).",
    whatToLookFor: ["semantic landmarks, lists, headings, tables, and their roles (use get_a11y_tree)"],
    passRequires: ["structure is programmatic (headings/lists/landmarks have correct roles)"],
    failRequires: ["relationships are conveyed only visually (e.g. styled <div> list, visual-only table header)"],
    ruleId: "ai-info-relationships",
    description: "Structure and relationships are not programmatically determined",
    recommendation: "Use semantic elements (list, heading, landmark, table) so relationships are programmatic.",
    help: "Structure and relationships must be programmatic",
    source: SOURCE("info-and-relationships"),
    notes: "agentic",
  }),
  "4.1.2": cfg("4.1.2", "4.1.2.2", "vision", {
    instruction: "User interface components expose their name, role, and value programmatically (and state changes are announced).",
    whatToLookFor: ["custom widgets' role/name/value and announced state (use get_a11y_tree, inspect_element)"],
    passRequires: ["controls have programmatic name/role/value and announce state changes"],
    failRequires: ["a custom widget lacks a programmatic name, role, or value"],
    ruleId: "ai-name-role-value",
    description: "A control lacks programmatic name/role/value",
    recommendation: "Expose name, role, and value via semantic HTML or ARIA.",
    help: "Controls must expose name, role, and value",
    source: SOURCE("name-role-value"),
    notes: "agentic",
  }),
};

export function getDefaultAiConfig(sc: string): ScAiConfig | undefined {
  return DEFAULT_AI_CONFIGS[sc];
}
