import type { ConformanceRow } from "@/components/assessment/types";

// Builds a printable Accessibility Conformance Report (ACR) in VPAT structure,
// generated from the per-criterion conformance data. Clearly labelled DRAFT —
// automated scan, partial coverage, not independently verified. It is honest
// about coverage so a user without human review still has something to show.

function esc(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function conformanceLabel(row: ConformanceRow): string {
  switch (row.result) {
    case "Passed":
      return "Supports";
    case "Failed":
      return "Does Not Support";
    case "NotPresent":
      return "Not Applicable";
    case "CannotTell":
      return "Not evaluated — needs human review";
    default:
      return "Not evaluated";
  }
}

function natureOf(row: ConformanceRow): string {
  if (row.machineResult === "Passed" || row.machineResult === "Failed") {
    return "Machine (automated)";
  }
  if (row.result === "CannotTell") return "Needs human review";
  if (row.result === "Passed" || row.result === "Failed") return "AI-assisted";
  return "—";
}

export interface AcrInput {
  url: string;
  standard: string;
  date: string;
  coverage: number;
  total: number;
  passed: number;
  failed: number;
  cannotTell: number;
  rows: ConformanceRow[];
}

export function buildAcrHtml(input: AcrInput): string {
  const resolved = input.passed + input.failed;
  const rows = input.rows
    .map(
      (row) => `<tr>
  <td>${esc(row.num)}</td>
  <td>${esc(row.title)}</td>
  <td>${esc(row.level)}</td>
  <td>${esc(conformanceLabel(row))}</td>
  <td>${esc(natureOf(row))}</td>
</tr>`,
    )
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Accessibility Conformance Report (Draft) — ${esc(input.url)}</title>
<style>
  body { font-family: system-ui, sans-serif; color: #1f2328; max-width: 900px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  h1 { font-size: 1.5rem; } h2 { font-size: 1.1rem; margin-top: 1.5rem; }
  .draft { border: 2px solid #b3541e; background: #fff7ed; padding: 0.75rem 1rem; border-radius: 4px; font-weight: 600; color: #8a3b00; }
  table { border-collapse: collapse; width: 100%; margin-top: 1rem; font-size: 0.85rem; }
  th, td { border: 1px solid #d0d7de; padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; }
  th { background: #f6f8fa; }
  dl { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 1rem; }
  dt { font-weight: 600; } dd { margin: 0; }
  .meta { color: #57606a; font-size: 0.85rem; }
</style>
</head>
<body>
  <h1>Accessibility Conformance Report (ACR)</h1>
  <p class="draft">DRAFT — automated scan &middot; partial coverage &middot; not independently verified. This is not a procurement-grade ACR.</p>

  <h2>Summary</h2>
  <dl>
    <dt>Product / URL</dt><dd>${esc(input.url)}</dd>
    <dt>Standard</dt><dd>${esc(input.standard)}</dd>
    <dt>Report date</dt><dd>${esc(input.date)}</dd>
    <dt>Coverage</dt><dd>${resolved} of ${input.total} criteria resolved by machine (${input.cannotTell} need human review)</dd>
    <dt>Evaluation method</dt><dd>Automated rule engine + AI-assisted review. Human review not yet performed (coming soon).</dd>
  </dl>

  <h2>Results by success criterion</h2>
  <p class="meta">Conformance levels follow the VPAT convention: Supports / Does Not Support / Not Applicable / Not evaluated.</p>
  <table>
    <thead>
      <tr><th>SC</th><th>Criterion</th><th>Level</th><th>Conformance</th><th>Tested by</th></tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>

  <p class="meta">Generated by Ascent Accessibility (ascent-partners.com). This draft is generated from automated results only and is not a statement of full WCAG conformance.</p>
</body>
</html>`;
}
