import Link from "next/link";
import type { Metadata } from "next";
import { LegalNote } from "@/components/legal/legal-note";

export const metadata: Metadata = {
  title: "Terms of service",
  description:
    "Terms of service for Ascent Accessibility, the free WCAG assessment tool by Ascent Partners Foundation.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="font-mono text-3xl font-bold text-terminal-fg">Terms of service</h1>
      <p className="mt-3 font-mono text-sm text-terminal-muted">Last updated: August 2026</p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">1. Who we are</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        Ascent Accessibility is operated by Ascent Partners Foundation Limited, a Hong Kong
        registered charity (IRD Section 88). These terms govern your use of the website and
        the accessibility assessment service (the &ldquo;Service&rdquo;).
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">2. The Service is an aid, not an audit</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        The Service runs automated checks against recognised standards such as WCAG 2.2. It
        is a self-assessment aid for awareness and remediation planning. It is{" "}
        <strong className="text-terminal-fg">not</strong> a certified accessibility audit, a
        statement of conformance, or legal advice. Automated tools detect only a subset of
        potential issues; some success criteria require manual testing. Do not rely on a
        score alone to establish legal compliance.
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">3. Accounts and subscriptions</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        Single-page assessments are free and do not require an account. Whole-website scans
        and API access require an active subscription, billed monthly in US dollars through
        Stripe. You are responsible for keeping your payment details current. Subscriptions
        renew automatically until cancelled — you can cancel at any time from the billing
        portal.
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">4. Acceptable use</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        You may scan only websites that you own or are authorised to assess. You agree not to
        use the Service to overwhelm, disrupt, or access systems you are not authorised to
        test, and not to resell the Service. We may rate-limit requests and may suspend or
        terminate access for misuse.
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">5. Intellectual property</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        Reports generated by the Service are provided for your internal use. The Service,
        its software, and its scoring methodology remain our property.
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">6. Disclaimer and liability</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without
        warranties of any kind. To the fullest extent permitted by law, we are not liable for
        indirect, incidental, or consequential loss arising from your use of the Service or
        from reliance on its results.
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">7. Governing law</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        These terms are governed by the laws of the Hong Kong Special Administrative Region.
      </p>

      <h2 className="mt-8 font-mono text-xl font-semibold text-terminal-fg">8. Contact</h2>
      <p className="mt-3 font-mono leading-7 text-terminal-muted">
        Questions about these terms:{" "}
        <a href="mailto:contact@ascent-partners.com" className="underline underline-offset-4 hover:text-terminal-fg">
          contact@ascent-partners.com
        </a>
        . See also our{" "}
        <Link href="/privacy" className="underline underline-offset-4 hover:text-terminal-fg">
          privacy policy
        </Link>
        .
      </p>

      <LegalNote label="terms of service" />
    </div>
  );
}
